-- MySQL Script generated by MySQL Workbench
-- 04/25/16 22:15:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_GenesysLab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_GenesysLab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_GenesysLab` DEFAULT CHARACTER SET utf8 ;
USE `BD_GenesysLab` ;

-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`Cargos` (
  `IdCargo` TINYINT(1) UNSIGNED NOT NULL,
  `NameCargo` VARCHAR(100) NOT NULL,
  `DescripcionCargo` VARCHAR(200) NULL,
  PRIMARY KEY (`IdCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`Dependencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`Dependencias` (
  `IdDependencia` TINYINT(1) NOT NULL,
  `NameDependencia` VARCHAR(100) NOT NULL,
  `DescripcionDependencia` VARCHAR(200) NULL,
  PRIMARY KEY (`IdDependencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`Personas` (
  `IdPersonas` BIGINT(1) UNSIGNED NOT NULL,
  `NamePersonas` VARCHAR(120) NOT NULL,
  `ApellidosPersonas` VARCHAR(120) NULL,
  `GeneroPersonas` VARCHAR(10) NOT NULL,
  `ProfesionPesonas` VARCHAR(100) NULL,
  `FotoPersonas` LONGBLOB NULL,
  `Cargos_IdCargo` TINYINT(1) UNSIGNED NOT NULL,
  `Dependencias_IdDependencia` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdPersonas`, `Cargos_IdCargo`, `Dependencias_IdDependencia`),
  INDEX `fk_Personas_Cargos1_idx` (`Cargos_IdCargo` ASC),
  INDEX `fk_Personas_Dependencias1_idx` (`Dependencias_IdDependencia` ASC),
  CONSTRAINT `fk_Personas_Cargos1`
    FOREIGN KEY (`Cargos_IdCargo`)
    REFERENCES `BD_GenesysLab`.`Cargos` (`IdCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personas_Dependencias1`
    FOREIGN KEY (`Dependencias_IdDependencia`)
    REFERENCES `BD_GenesysLab`.`Dependencias` (`IdDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`Modulos` (
  `IdModulo` TINYINT(1) NOT NULL,
  `NameModulo` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`IdModulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`Historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`Historiales` (
  `SerialHistorial` BIGINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `HoraEntrada` DATETIME(1) NOT NULL,
  `HoraSalida` DATETIME(1) NOT NULL,
  `Personas_IdPersonas` BIGINT(1) UNSIGNED NOT NULL,
  `Modulos_IdModulo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`SerialHistorial`, `Personas_IdPersonas`, `Modulos_IdModulo`),
  INDEX `fk_Historiales_Personas1_idx` (`Personas_IdPersonas` ASC),
  INDEX `fk_Historiales_Modulos1_idx` (`Modulos_IdModulo` ASC),
  CONSTRAINT `fk_Historiales_Personas1`
    FOREIGN KEY (`Personas_IdPersonas`)
    REFERENCES `BD_GenesysLab`.`Personas` (`IdPersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historiales_Modulos1`
    FOREIGN KEY (`Modulos_IdModulo`)
    REFERENCES `BD_GenesysLab`.`Modulos` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_GenesysLab`.`SystemAdmins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_GenesysLab`.`SystemAdmins` (
  `IdAdmin` BIGINT(1) UNSIGNED NOT NULL,
  `NombreAdmin` VARCHAR(120) NOT NULL,
  `ApellidosAdmin` VARCHAR(120) NULL,
  `PassAdmin` BLOB NOT NULL,
  `FotoAdmin` LONGBLOB NULL,
  PRIMARY KEY (`IdAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
